### ISSUE TITLE
Source code directories

### ISSUE THREAD

**Issue by mortenvp** [LoopPerfect/rxterm#10]
Hi all,
Looks like a great library :) we have one problem using it though. Let me try to explain:

In our projects we clone the repositories and set include paths directly to the directories within. However, this is not possible with RxTerm since it has includes in `rxterm/includes`. We could do `#include <rxterm/includes/terminal.hpp>` in our source code but that also does not work since `terminal.hpp` itself expects other RxTerm headers to be under `#include <rxterm/header_file.hpp>` etc. 

So basically to make the library easier to consume a suggestion would be to move the `includes` and `app` folder to the top-level dir. Such that it would become something like this:

```
├── apps
│   └── main.cpp
├── BUCK
├── buckaroo.lock.toml
├── buckaroo.toml
├── include
│   └── rxterm
│       ├── components
│       │   ├── component.hpp
│       │   ├── flowlayout.hpp
│       │   ├── maxwidth.hpp
│       │   ├── progress.hpp
│       │   ├── stacklayout.hpp
│       │   └── text.hpp
│       ├── image.hpp
│       ├── pixel.hpp
│       ├── reflow.hpp
│       ├── style.hpp
│       ├── terminal.hpp
│       └── utils.hpp
├── LICENSE
├── README.md
├── subdir_glob.bzl
└── travis
    ├── before-install-linux.sh
    └── before-install-osx.sh

```

In this way you can just set your includes to the `include` directory and everything should work.

Views?

**Comment by nikhedonia** [comment]
Thanks for sharing your thoughts. 
Indeed our current folder structure is only convenient for buildsystems that have hermetic builds like buck and bazel. It should be easy to change. I'll follow up with a PR shortly

**Comment by mortenvp** [comment]
Hi @nikhedonia that sounds great. Will look forward :)

**Comment by njlr** [comment]
> Thanks for sharing your thoughts.
> Indeed our current folder structure is only convenient for buildsystems that have hermetic builds like buck and bazel. It should be easy to change. I'll follow up with a PR shortly

I think Bazel will also require this change (to work in a convenient way) since it doesn't offer the same control over headers that Buck does.

**Comment by njlr** [comment]
https://github.com/LoopPerfect/rxterm/pull/11

**Comment by mortenvp** [comment]
Cool guys - thanks!
