### ISSUE TITLE
Don't reset BG after Progress

### ISSUE THREAD

**Issue by o-kos** [LoopPerfect/rxterm#17]
Adding Text component after Progress make invalid background color for text (attachment).
```C++
  auto superProgressBar = [](auto x, auto y, auto z) -> FlowLayout<> {
    return {
      Text("3 segment progressbar: "),
      FlowLayout<>{
        MaxWidth(20, Progress(x)),
        MaxWidth(20, Progress(y)),
        MaxWidth(20, Progress(z))
      },
      Text("after progress")
    };
  };
```
![image](https://user-images.githubusercontent.com/16743428/101787222-e657e400-3b0f-11eb-9404-258294132eff.png)

**Comment by o-kos** [comment]
```C++
Text({Color::Yellow}, "3 segment progressbar: "),
Text{{FontColor::Magenta}, "second text"},
```

This code also paint "second text" with yellow bg color

**Comment by nikhedonia** [comment]
Nice find!
Just to double check: is in this case "after progress" on top of the progress bar, or next but just with the same background?
if it's the latter then I guess we should reset the text style

**Comment by o-kos** [comment]
This code 
```C++
Text({Color::Yellow}, "string1"),
Text{{FontColor::Magenta}, "string2"},
```
is converted to this string
```
 \033[43mstring1\033[39;35mstring2
```

IMHO, error in this part: 
```[39;``` - Set default color as **foreground** color, but must be ```[49;``` - Set default color as **background** color.

I try to fix this.

**Comment by o-kos** [comment]
1. What means "None", "Transparent" and "Inherit" colors?
2. Why default value for bg color is "None", but for fg color - "Inherit"?

For "None" color functions bgMod() && fgMod() worked incorrectly
```C++
  string bgMod() const {
    return ((int)bg<11) ? std::to_string(40 + (int)bg -1) : "";
  }

  string fgMod() const {
    return ((int)fg<11) ? std::to_string(30 + (int)fg -1) : "";
  }
```
bgMod() for bg=11 return 39 -> ```[39;``` - ESC code for set default color as **foreground** color
fgMod() for fg=11 return 29 -> ```[29;```  - **Undefined ESC code**
