### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by DBJDBJ** [LoopPerfect/rxterm#4]
if for windows redstone 4 onwards and for windows bash only 

1. might actually work on Windows
2. would be perfect for using modern C++ instead of bash shell scripts
3. would require Visual Studio target(s) for building modern C++ console for rxterm bash windows app's

DBJ

**Comment by LoganDark** [comment]
Use WSL.

Windows is not terminal-focused. Windows uses a simplified GUI interface for everyday users. The command prompt is rarely used. IDEs have simple GUI interfaces for all of this.

WSL is for people who want a real terminal. And this library works(?) in WSL. I don't see the issue here.

**Comment by nikhedonia** [comment]
We havn't tested this library on Windows.
The implementation uses hardcoded terminal escape sequences that are (linux?)bash specific.
Based on that I'd assume it woudn't work on Windows cmd but very likely on WSL.

The next iteration of this library would be to use an abstraction over those escape sequences.
There are a couple libraries out there that abstract over terminals and escape sequences.

Ideally we would add support for custom renderers to make this library work on different IO devices / platforms.

I'm happy to discuss this further or accept a PR.

**Comment by LoganDark** [comment]
Doesn't Windows 10 have support for some escape sequences anyway?

**Comment by nikhedonia** [comment]
I found this library: https://github.com/adoxa/ansicon
Seems like the purpose is to translate ANSI escape sequences to windows equivalents.

According to https://superuser.com/a/1105718
ANSI codes were not supported before Win10

**Comment by misuo** [comment]
Check https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

**Comment by LoganDark** [comment]
> ANSI codes were not supported before Win10

@nikhedonia That's why I specifically said Windows 10. Even more specifically, the Anniversary Update.

---

I don't think this is an issue that this library needs to address. You'd be adding unnecessary bulk for Windows console support even though it's rarely used and in general much less featureful than the Linux ones.

I think there are enough programs out there that can translate escape sequences in post that you can pretty much use any of those. You can also use WSL, or a virtual machine. You could even just not use Windows.

My preferred solution would be the latter, however, feel free to use any of them.

**Comment by xclydx12x** [comment]
this works on windows. simply include the include folder and code.

**Comment by LoganDark** [comment]
@AnonAmazing This library works as long as whatever you're running it in understands the escape sequences that it uses. You can totally use this library under Windows, as I believe Command Prompt understands some ANSI escapes now. But I don't believe it's fully functional.

**Comment by LoganDark** [comment]
As a quick note, ANSI escapes are not bash, Linux or even operating system specific. They're terminal specific, and Windows does not have a very good terminal by default. Install a terminal that recognizes ANSI escapes and this library will work just fine on Windows. Try alacritty.

**Comment by nikhedonia** [comment]
Thanks for your suggestion @LoganDark Alacritty looks interesting!

**Comment by LoganDark** [comment]
This issue can be closed if alacritty works or possibly edited to mean "Windows _console_ support" if you need/want support for their special console that requires system calls. @DBJDBJ

**Comment by xclydx12x** [comment]
using WSL works, u'all should use it. And, I think windows support will be available in future versions.

**Comment by LoganDark** [comment]
@AnonAmazing 1. we know, and 2. not likely.

**Comment by xclydx12x** [comment]
@LoganDark what's not likely?

**Comment by LoganDark** [comment]
@AnonAmazing we know wsl works and windows console support is not likely.

**Comment by xclydx12x** [comment]
@LoganDark yeah but i think there are libraries that can help with that

**Comment by xclydx12x** [comment]
@LoganDark i think the developers would want to work on a library that does the support

**Comment by LoganDark** [comment]
@AnonAmazing Yes, like how colorama does it for Python.

**Comment by xclydx12x** [comment]
@LoganDark i think i can help with developing this support library

**Comment by LoganDark** [comment]
@AnonAmazing PRs are most likely welcome.

**Comment by xclydx12x** [comment]
@LoganDark tnx

**Comment by xclydx12x** [comment]
@LoganDark i opened an issue about it

**Comment by LoganDark** [comment]
There are two ways to go about this:

1. Translating escape sequences to win32 calls like colorama does.
2. Rewriting the entire library to support either ANSI escape sequences or win32 calls.

I would personally recommend the former as it does not pollute the entire library with win32 stuff.

It could be possible to look into how colorama does the translation and build that into rxterm, so applications built for Windows can use that.

**Comment by xclydx12x** [comment]
@nikhedonia i forked rxterm. i'll focus on trying to create one that supports windows

**Comment by xclydx12x** [comment]
where exactly are the ANSI escape sequence?

**Comment by nikhedonia** [comment]
Thank your guys for looking into this.

Escape sequences show up in couple places eg.:
https://github.com/LoopPerfect/rxterm/blob/master/rxterm/include/style.hpp
https://github.com/LoopPerfect/rxterm/blob/master/rxterm/include/utils.hpp#L57

I guess one would need to refactor and abstract over the differences between windows and linux

**Comment by xclydx12x** [comment]
> Thank your guys for looking into this.
> 
> Escape sequences show up in couple places eg.:
> https://github.com/LoopPerfect/rxterm/blob/master/rxterm/include/style.hpp
> https://github.com/LoopPerfect/rxterm/blob/master/rxterm/include/utils.hpp#L57

thanks

**Comment by xclydx12x** [comment]
now i know what they look like.

I'm gonna start by searching for c++ alternatives

**Comment by LoganDark** [comment]
@AnonAmazing It should be easy to include the Windows headers and make the necessary system calls from C++. The tricky part is probably catching the output and translating it that way before it's output. In order to do that, you may have to redirect the global stdout through your console handler or translate before you print.

I'd recommend leaving out the constant status updates, though; I receive an email for every single one and I'm pretty close to unsubscribing from this thread from all the noise. Please consider using Discord or Slack or Gitter or some other IM solution to prevent cluttering up the issue tracker.

**Comment by xclydx12x** [comment]
i think we can close this now

**Comment by LoganDark** [comment]
That's not how issues work. Issues stay open until they are solved. This is not yet solved; it will be solved when you open a PR that adds windows support, and get it merged into this repository.

**Comment by xclydx12x** [comment]
ok

> That's not how issues work. Issues stay open until they are solved. This is not yet solved; it will be solved when you open a PR that adds windows support, and get it merged into this repository.

ok

**Comment by xclydx12x** [comment]
hex '\x' code could work

**Comment by xclydx12x** [comment]
we could use this
example: `\x1B[47;34mHello, world!\x1B[0m`

**Comment by xclydx12x** [comment]
i have added a new pull request that could fix the windows support problem

**Comment by nikhedonia** [comment]
Thanks @AnonAmazing. I'm a bit surprised that it was so simple. Are you sure this does the Job? 
\e means escape in ascii and has the hex code 1B; in my understanding \x allows you to embed any hexcode in c++, consequently \x1B would represent and compile to the exact same value.

See here: https://godbolt.org/z/6bMbbd

**Comment by xclydx12x** [comment]
There are many examples the can be found in stackoverflow.com about `\x1B` being used in windows @nikhedonia

**Comment by xclydx12x** [comment]
this repo is dying now

**Comment by DBJDBJ** [comment]
> 
> 
> this repo is dying now

(If there is a leadership) One would like to see some roadmap perhaps?

**Comment by nikhedonia** [comment]
> There are many examples the can be found in stackoverflow.com about \x1B being used in windows @nikhedonia

Have you looked into the Godbolt snippet? - your PR is not changing anything it yields exactly identical binary bit by bit. 
If this is supposed to work than this library should already work.

According to this blog post VT100 support is implemented in windows but disabled by default:
https://larsfosdal.blog/2018/08/31/did-you-know-that-you-can-enable-vt100-terminal-emulation-in-powershell-as-well-as-the-cmd-window/

It appears that one needs to call `SetConsoleMode()` to activate it for your process or `reg add HKCU\Console /v VirtualTerminalLevel /t REG_DWORD /d 1` to enable it globally.

I'm happy to accept a solution that works but it seems like windows is already supported once your terminal app is configured correctly.

> One would like to see some roadmap perhaps?

We implemented this library internally for some specific usecases and opensourced it will be of use to somebody.
Currently I don't have a roadmap I can commit to for this project.

**Comment by DBJDBJ** [comment]
@nikhedonia  many thanks.  Err, yes  WIN10 cmd.exe should have VT100 escape codes support by default switched on. But somehow **sometimes**, it does not. I am the eye witness but I can not explain what I have seen (laugh). Thus, I have attached, one cmd and one reg file. Same as I am using in my console projects. In case WIN10 cmd.exe stops behaving.

[DBJ_VT100_WIN_TOOLS.zip](https://github.com/LoopPerfect/rxterm/files/5294177/DBJ_VT100_WIN_TOOLS.zip)

**Comment by nikhedonia** [comment]
@DBJDBJ Have you tried to follow the suggestions in the blog post?

> Err, yes WIN10 cmd.exe should have VT100 escape codes support by default switched on

As far as I know, by default it's  **off** and is also hinted that it needs to be enabled in the first paragraph in the MSDN:
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

I remember that VT100 support was added to windows 10 via an update and was only available in the "developer preview" for a while...

Also I found people suggesting that a call to `system("")` with an empty string seem to enable VT100 codes:
https://stackoverflow.com/questions/51091680/activating-vt100-via-os-system

Would be great to get to the bottom of this. 
My research suggests that it should work for cmd.exe and powershell in an up to date windows provided it has been enabled either globally or on a process level.

**Comment by DBJDBJ** [comment]
By default and by now WIN10 PRO cmd.exe VT100 correct interpretation is to be in existence and working always. Sometimes it does not.

[win32_console.zip](https://github.com/LoopPerfect/rxterm/files/5295045/win32_console.zip)
contains two functions. One to enable the console for VT100, the other to change the font.

[vt100win10.zip](https://github.com/LoopPerfect/rxterm/files/5295057/vt100win10.zip)
contains VT100 escape codes string literals I am using.

I am "colouring the consoles" all the time using these two:

![dbj_tu_in_action](https://user-images.githubusercontent.com/145155/94486740-216c9b80-01e0-11eb-9ead-d54b233b9369.jpg)

Please ask if you are not clear about something inside.


.

**Comment by DBJDBJ** [comment]
> Also I found people suggesting that a call to `system("")` with an empty string seem to enable VT100 codes:
> https://stackoverflow.com/questions/51091680/activating-vt100-via-os-system

that is true. just please make sure it is a single space .... empty string crashes the MSVC

**Comment by nikhedonia** [comment]
I finally managed to test it on windows 10 and I conclude the library works as-it-is on windows as under cygwin, msys2 and cmd.exe although the latter one needed explicit activation of terminal codes. This can be done by calling system(" ").

![rxterm-windows](https://user-images.githubusercontent.com/4670055/95693090-5b29a300-0bdf-11eb-9d17-9702054d43ef.png)
