### ISSUE TITLE
creation of rxterm support library for windows. "rxterm-msw"

### ISSUE THREAD

**Issue by xclydx12x** [LoopPerfect/rxterm#8]
we should create a library that offers windows 10 support for rxterm. "rxterm-msw"

**Comment by LoganDark** [comment]
There's already an issue open for this. #4 

You can discuss your potential solutions there, but please do not open new duplicate issues

**Comment by xclydx12x** [comment]
this is for creating the library

**Comment by LoganDark** [comment]
@AnonAmazing #4 is for windows support. Discussion of the library should go there. Please do not open duplicate issues

**Comment by xclydx12x** [comment]
ok
